force-app/main/default/objects/Compliance_Document_Assignment__c/Compliance_Document_Assignment__c.object-meta.xml
<CustomObject>
    <description>Will contain compliance documents that need to be shared to other objects but only be visible to selected users.</description>
    <label>Compliance Document Assignment</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Compliance Document Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Document Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Document_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Record lookup to related Account.</description>
    <inlineHelpText>Record lookup to related Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compliance Document Assignments</relationshipLabel>
    <relationshipName>Compliance_Document_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Document_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Contact.</description>
    <inlineHelpText>Lookup to related Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compliance Document Assignments</relationshipLabel>
    <relationshipName>Compliance_Document_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplianceDocumentController.cls
public without sharing class ComplianceDocumentController {
    @AuraEnabled(cacheable=false)
    public static void createComplianceDocument(string recordId, string type, string fileId) {
        try {
            // --- Create Compliance Document ---
            Compliance_Document_Assignment__c complainceDocument = new Compliance_Document_Assignment__c();
            if (type == 'Account') {
                complainceDocument.Account__c = recordId;
            }
            else if(type == 'Contact') {
                complainceDocument.Contact__c = recordId;
            }
            insert complainceDocument;

            // --- Assign File to New Compliance Document ---
            ContentDocumentLink documentLink = new ContentDocumentLink();
            documentLink.ContentDocumentId = fileId;
            documentLink.LinkedEntityId = complainceDocument.Id;
            insert documentLink;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}